sudo: false
language: c
addons:
  apt:
    packages:
      - rake
      - bison
      - git
      - gperf

compiler:
  - gcc
  - clang
env:
  # - MRUBY_VERSION=1.2.0
  - MRUBY_VERSION=1.3.0
  - MRUBY_VERSION=master
script:
  - rake format
  - rake test
branches:
  only:
    - master
